name: debian-fish-bulls-eye docker container image creation
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 18 * * *'
jobs:
  push_to_registry:
    name: Build docker image from Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Set container image name
        run: echo "::set-output name=container-image::debian-fish"
        id: container
      - name: Set container tag
        run: echo "::set-output name=container-tag::bulls-eye"
        id: container
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker
          tags: ghcr.io/${{ github.repository_owner }}/${{ steps.container.outputs.container-image }}:${{ steps.container.outputs.container-tag }}
