name: debian11-fish docker image creation
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 18 * * *'
jobs:
  push_to_registry:
    name: Build Docker image from Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
        run: echo "::set-output name=CONTAINER_NAME::debian11-fish"
        id: get-branch-name
      - name: Show Branch Name
        run: echo ${{ steps.get-branch-name.outputs.CONTAINER_NAME }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPONAME }}/${{ steps.get-branch-name.outputs.CONTAINER_NAME }}:latest
